import { testAccountId, testEmployeeId } from "@tests/api/support/test-identity-id"

/** 社員を指す列。数字の社員 ID は seed と同じ規則で UUID へ写す。 */
const EMPLOYEE_COLUMNS = new Set([
  "announcements.author_employee_id",
  "antisocial_checks.requester_id",
  "asset_lendings.employee_id",
  "assets.holder_employee_id",
  "attendance_records.employee_id",
  "business_trips.traveler_id",
  "career_applications.applicant_id",
  "career_sheets.employee_id",
  "certificate_requests.requester_id",
  "commendations.employee_id",
  "company_account_employee_links.employee_id",
  "company_account_employee_resource_bindings.employee_id",
  "company_assignment_resource_adoptions.employee_id",
  "company_assignment_resource_bindings.employee_id",
  "company_audit_event_appends.actor_employee_id",
  "company_audit_event_employee_contexts.employee_id",
  "company_bootstrap_receipts.employee_id",
  "company_employee_lifecycle_revisions.employee_id",
  "company_employee_resource_adoptions.employee_id",
  "company_employee_status_period_versions.employee_id",
  "company_employees.id",
  "company_employment_period_versions.employee_id",
  "company_employments.employee_id",
  "company_grade_award_archives.employee_id",
  "company_organization_assignment_period_versions.employee_id",
  "company_organization_assignment_period_versions.manager_employee_id",
  "company_organization_responsibility_period_versions.employee_id",
  "company_personnel_action_requests.requested_by_employee_id",
  "company_personnel_action_requests.target_employee_id",
  "company_personnel_action_requests.withdrawn_by_employee_id",
  "company_personnel_actions.employee_id",
  "company_personnel_actions.requested_by_employee_id",
  "company_personnel_annotations.employee_id",
  "company_personnel_reporting_bindings.employee_id",
  "company_responsibility_resource_adoptions.employee_id",
  "company_responsibility_resource_bindings.employee_id",
  "company_workforce_resource_bindings.employee_id",
  "disciplinary_actions.employee_id",
  "employee_certifications.employee_id",
  "employee_skills.employee_id",
  "employee_work_styles.employee_id",
  "evaluation_sheet_audit_logs.actor_id",
  "evaluation_sheets.employee_id",
  "evaluation_sheets.primary_evaluator_id",
  "evaluation_sheets.secondary_evaluator_id",
  "evaluation_templates.created_by",
  "expense_approvals.approver_id",
  "expenses.employee_id",
  "family_care_leaves.employee_id",
  "goal_evaluations.evaluator_id",
  "governance_acknowledgements.employee_id",
  "governance_org_role_assignments.employee_id",
  "governance_publication_approvals.decided_by_employee_id",
  "health_checkups.employee_id",
  "knowledge_articles.author_id",
  "leave_balances.employee_id",
  "leave_requests.approver_id",
  "leave_requests.employee_id",
  "life_events.employee_id",
  "meeting_minutes_records.author_employee_id",
  "onboarding_assignments.employee_id",
  "one_on_ones.manager_id",
  "one_on_ones.member_id",
  "performance_goals.employee_id",
  "rental_reservations.requester_id",
  "resignations.employee_id",
  "review_forms.reviewer_employee_id",
  "review_forms.subject_employee_id",
  "ringi_requests.applicant_id",
  "ringi_requests.approver_id",
  "room_reservations.reserver_id",
  "salary_revisions.employee_id",
  "shift_assignments.employee_id",
  "shift_swap_requests.requester_employee_id",
  "shift_swap_requests.target_employee_id",
  "software_license_assignments.employee_id",
  "software_licenses.owner_employee_id",
  "stocktake_items.checker_employee_id",
  "survey_responses.respondent_id",
  "thanks_messages.recipient_employee_id",
  "thanks_messages.sender_employee_id",
  "thanks_point_budgets.employee_id",
  "thanks_redemptions.decider_id",
  "thanks_redemptions.employee_id",
  "training_enrollments.employee_id",
  "work_accidents.employee_id",
])
/** Account を指す列。 */
const ACCOUNT_COLUMNS = new Set([
  "company_account_employee_links.account_id",
  "company_account_employee_resource_bindings.account_id",
  "company_account_profiles.account_id",
  "company_assignment_resource_adoptions.actor_account_id",
  "company_audit_event_appends.actor_account_id",
  "company_audit_events.actor_account_id",
  "company_bootstrap_receipts.actor_account_id",
  "company_definition_resource_adoptions.actor_account_id",
  "company_employee_resource_adoptions.actor_account_id",
  "company_external_identity_imports.actor_account_id",
  "company_grade_award_archives.actor_account_id",
  "company_organization_change_operations.actor_account_id",
  "company_organization_resource_adoptions.actor_account_id",
  "company_personnel_actions.recorded_by_account_id",
  "company_profile_change_receipts.actor_account_id",
  "company_resource_revisions.actor_account_id",
  "company_responsibility_resource_adoptions.actor_account_id",
  "company_responsibility_source_adoptions.actor_account_id",
  "company_responsibility_source_cutovers.actor_account_id",
  "company_workforce_connection_completions.actor_account_id",
  "governance_document_versions.created_by_account_id",
  "governance_document_versions.published_by_account_id",
  "governance_documents.created_by_account_id",
  "governance_org_role_assignments.created_by_account_id",
  "governance_org_role_assignments.revoked_by_account_id",
  "knowledge_article_revisions.actor_account_id",
  "onboarding_lifecycle_template_bindings.updated_by_account_id",
  "software_license_assignments.account_reference",
  "software_license_assignments.assigned_by",
  "software_license_assignments.released_by",
  "software_license_changes.actor_account_id",
  "system_account_invitations.accepted_by_account_id",
  "system_accounts.id",
  "system_attachment_preservations.created_by_account_id",
  "system_attachment_preservations.released_by_account_id",
  "system_attachments.owner_account_id",
  "system_audit_disclosure_policy_revisions.actor_account_id",
  "system_audit_events.actor_account_id",
  "system_bootstrap_state.completed_by_account_id",
  "system_browser_login_codes.account_id",
  "system_cases.created_by_account_id",
  "system_cli_login_codes.account_id",
  "system_decision_task_candidates.candidate_account_id",
  "system_decision_task_exclusions.excluded_account_id",
  "system_delegations.delegate_account_id",
  "system_delegations.delegator_account_id",
  "system_execution_authorizations.granted_to_account_id",
  "system_human_attestations.actor_account_id",
  "system_human_attestations.represented_account_id",
  "system_identity_bindings.account_id",
  "system_jobs.created_by_account_id",
  "system_jobs.lease_account_id",
  "system_notification_deliveries.recipient_account_id",
  "system_oidc_access_tokens.account_id",
  "system_oidc_authorization_codes.account_id",
  "system_operation_receipts.actor_account_id",
  "system_outbox_messages.created_by_account_id",
  "system_outbox_messages.lease_account_id",
  "system_password_reset_challenges.account_id",
  "system_principals.account_id",
  "system_procedure_definition_revisions.created_by_account_id",
  "system_proposal_series.created_by_account_id",
  "system_proposals.created_by_account_id",
  "system_role_bindings.account_id",
  "system_sessions.account_id",
  "system_step_up_grants.account_id",
  "system_work_evidence.submitted_by_account_id",
  "system_work_item_revisions.accountable_account_id",
  "system_work_item_revisions.actor_account_id",
  "system_work_item_revisions.assignee_account_id",
  "system_work_items.created_by_account_id",
])

function identityValue(
  table: string,
  column: string,
  value: string | number | boolean | null | undefined,
): string | number | boolean | null {
  if (value === undefined || value === null) return null
  const numeric = typeof value === "number" || (typeof value === "string" && /^\d+$/u.test(value))
  if (!numeric) return value
  if (EMPLOYEE_COLUMNS.has(`${table}.${column}`)) return testEmployeeId(value as number | string)
  if (ACCOUNT_COLUMNS.has(`${table}.${column}`)) return testAccountId(value as number | string)
  return value
}

/** テスト用: snake_case の行オブジェクト配列を D1 のテーブルへ INSERT する。 */
export async function seedD1(
  db: D1Database,
  table: string,
  rows: ReadonlyArray<Record<string, string | number | boolean | null>>,
): Promise<void> {
  for (const row of rows) {
    const columns = Object.keys(row)

    if (columns.length === 0) {
      continue
    }

    const placeholders = columns.map(() => "?").join(", ")

    const sql = `INSERT INTO ${table} (${columns.join(", ")}) VALUES (${placeholders})`

    await db
      .prepare(sql)
      .bind(...columns.map((column) => identityValue(table, column, row[column])))
      .run()
  }
}
