-- 公開Company履歴へ保存する開発用の定義サンプル。
INSERT INTO "company_command_receipts" ("organization_id", "command_id", "fingerprint", "expected_revision", "organization_revision", "recorded_at") values ('organization:default', 'seed:grade:definitions', '579ceda65e72810197a0d4d77d3f2c5e14b9d6a6504153b0e731f02115e017ed', 1, 2, 1767225600000);
INSERT INTO "company_resource_revisions" ("organization_id", "resource_type", "resource_id", "revision", "organization_revision", "state", "effective_from", "effective_to", "attributes_json", "command_id", "actor_account_id", "reason", "recorded_at") values ('organization:default', 'grade', 'grade:seed:G1', 1, 2, 'active', '2026-01-01', NULL, '{"code":"G1","description":"初級","officialName":"一般職","rank":1}', 'seed:grade:definitions', '1', '開発用の定義サンプル', 1767225600000);
INSERT INTO "company_resource_heads" ("organization_id", "resource_type", "resource_id", "revision", "organization_revision", "state", "effective_from", "effective_to", "attributes_json", "updated_at") values ('organization:default', 'grade', 'grade:seed:G1', 1, 2, 'active', '2026-01-01', NULL, '{"code":"G1","description":"初級","officialName":"一般職","rank":1}', 1767225600000) on conflict ("company_resource_heads"."organization_id", "company_resource_heads"."resource_type", "company_resource_heads"."resource_id") do update set "revision" = excluded.revision, "organization_revision" = excluded.organization_revision, "state" = excluded.state, "effective_from" = excluded.effective_from, "effective_to" = excluded.effective_to, "attributes_json" = excluded.attributes_json, "updated_at" = excluded.updated_at;
INSERT INTO "company_resource_revisions" ("organization_id", "resource_type", "resource_id", "revision", "organization_revision", "state", "effective_from", "effective_to", "attributes_json", "command_id", "actor_account_id", "reason", "recorded_at") values ('organization:default', 'grade', 'grade:seed:G2', 1, 2, 'active', '2026-01-01', NULL, '{"code":"G2","description":"中級","officialName":"中堅職","rank":2}', 'seed:grade:definitions', '1', '開発用の定義サンプル', 1767225600000);
INSERT INTO "company_resource_heads" ("organization_id", "resource_type", "resource_id", "revision", "organization_revision", "state", "effective_from", "effective_to", "attributes_json", "updated_at") values ('organization:default', 'grade', 'grade:seed:G2', 1, 2, 'active', '2026-01-01', NULL, '{"code":"G2","description":"中級","officialName":"中堅職","rank":2}', 1767225600000) on conflict ("company_resource_heads"."organization_id", "company_resource_heads"."resource_type", "company_resource_heads"."resource_id") do update set "revision" = excluded.revision, "organization_revision" = excluded.organization_revision, "state" = excluded.state, "effective_from" = excluded.effective_from, "effective_to" = excluded.effective_to, "attributes_json" = excluded.attributes_json, "updated_at" = excluded.updated_at;
INSERT INTO "company_resource_revisions" ("organization_id", "resource_type", "resource_id", "revision", "organization_revision", "state", "effective_from", "effective_to", "attributes_json", "command_id", "actor_account_id", "reason", "recorded_at") values ('organization:default', 'grade', 'grade:seed:G3', 1, 2, 'active', '2026-01-01', NULL, '{"code":"G3","description":null,"officialName":"上級職","rank":3}', 'seed:grade:definitions', '1', '開発用の定義サンプル', 1767225600000);
INSERT INTO "company_resource_heads" ("organization_id", "resource_type", "resource_id", "revision", "organization_revision", "state", "effective_from", "effective_to", "attributes_json", "updated_at") values ('organization:default', 'grade', 'grade:seed:G3', 1, 2, 'active', '2026-01-01', NULL, '{"code":"G3","description":null,"officialName":"上級職","rank":3}', 1767225600000) on conflict ("company_resource_heads"."organization_id", "company_resource_heads"."resource_type", "company_resource_heads"."resource_id") do update set "revision" = excluded.revision, "organization_revision" = excluded.organization_revision, "state" = excluded.state, "effective_from" = excluded.effective_from, "effective_to" = excluded.effective_to, "attributes_json" = excluded.attributes_json, "updated_at" = excluded.updated_at;
UPDATE "company_organizations" set "revision" = 2, "updated_at" = 1767225600000 where ("company_organizations"."id" = 'organization:default' and "company_organizations"."revision" = 1);

-- 雇用・終了日が不明な旧付与サンプルは、期間付き割当へ推測変換せず原記録として保持する。
INSERT INTO company_grade_award_archives (organization_id,command_id,employee_id,fingerprint,actor_account_id,reason,observed_on,observed_company_revision,snapshot_digest,source_json,recorded_at) VALUES ('organization:default','seed:grade-archive:5','5','c2e9d370f419926d7aa6d425492992dc004e4dae4c2bbf8dc9c18165d3667df4','1','開発用の旧付与原記録','2026-06-01',2,'c2e9d370f419926d7aa6d425492992dc004e4dae4c2bbf8dc9c18165d3667df4','{"organizationRevision":2,"employeeId":"5","awards":[{"id":1,"employeeId":"5","gradeId":2,"effectiveDate":"2025-04-01","reason":"初回設定","createdAt":"2025-04-01T00:00:00.000Z","observedDefinition":{"id":2,"code":"G2","name":"中堅職","rank":2,"description":"中級","createdAt":"2026-01-01T00:00:00.000Z"}},{"id":2,"employeeId":"5","gradeId":3,"effectiveDate":"2026-04-01","reason":"昇格","createdAt":"2026-04-01T00:00:00.000Z","observedDefinition":{"id":3,"code":"G3","name":"上級職","rank":3,"description":null,"createdAt":"2026-01-01T00:00:00.000Z"}}]}',1780272000000);
INSERT INTO company_grade_award_archives (organization_id,command_id,employee_id,fingerprint,actor_account_id,reason,observed_on,observed_company_revision,snapshot_digest,source_json,recorded_at) VALUES ('organization:default','seed:grade-archive:9','9','1943d92ebfe407d2178181180cbf24c1ddb060a0a621c56c5bdba593dd3ada12','1','開発用の旧付与原記録','2026-06-01',2,'1943d92ebfe407d2178181180cbf24c1ddb060a0a621c56c5bdba593dd3ada12','{"organizationRevision":2,"employeeId":"9","awards":[{"id":3,"employeeId":"9","gradeId":1,"effectiveDate":"2025-04-01","reason":null,"createdAt":"2025-04-01T00:00:00.000Z","observedDefinition":{"id":1,"code":"G1","name":"一般職","rank":1,"description":"初級","createdAt":"2026-01-01T00:00:00.000Z"}}]}',1780272000000);
