import {
  Award,
  Bell,
  BookOpen,
  BookOpenCheck,
  Boxes,
  Briefcase,
  Building2,
  CalendarClock,
  CalendarDays,
  CalendarOff,
  ClipboardCheck,
  ClipboardList,
  Coins,
  DoorOpen,
  FileClock,
  FileText,
  GitBranch,
  GraduationCap,
  HandHelping,
  HeartHandshake,
  Inbox,
  KeyRound,
  Laptop,
  LayoutDashboard,
  MessagesSquare,
  Package,
  PartyPopper,
  Plane,
  ScrollText,
  Settings,
  ShieldCheck,
  Sparkles,
  Target,
  TimerReset,
  TriangleAlert,
  UserCog,
  UserMinus,
  Users,
  Wallet,
  Wrench,
} from "lucide-react"
import type {
  FeatureDefinition,
  FeatureGroup,
  FeatureNavigationVisibility,
  FeatureStatus,
  FeatureTier,
} from "@/lib/feature/feature-types"

const everyone: FeatureNavigationVisibility = { kind: "everyone" }

/**
 * 開発中はユーザ視点の利用レビューが完了していない機能を含む。
 */
export const featureRegistry: ReadonlyArray<FeatureDefinition> = [
  {
    slug: "dashboard",
    tier: "company",
    status: "available",
    group: "overview",
    icon: LayoutDashboard,
    prefetch: null,
    routes: [{ space: "my", label: "マイページ", href: "/my", visibility: everyone }],
  },
  {
    slug: "inbox",
    tier: "company",
    status: "available",
    group: "overview",
    icon: Inbox,
    prefetch: null,
    routes: [{ space: "my", label: "受信箱", href: "/inbox", visibility: everyone }],
  },
  {
    slug: "notifications",
    tier: "system",
    status: "available",
    group: "overview",
    icon: Bell,
    prefetch: null,
    routes: [{ space: "my", label: "通知", href: "/notifications", visibility: everyone }],
  },
  {
    slug: "attendance",
    tier: "app-default",
    status: "development",
    group: "time",
    icon: TimerReset,
    prefetch: null,
    routes: [
      { space: "my", label: "勤怠", href: "/my/attendances", visibility: everyone },
      {
        space: "teams",
        label: "勤怠",
        href: "/teams/:team/attendances",
        visibility: {
          kind: "any-permission",
          permissions: ["attendance:read:department", "attendance:read:all"],
        },
      },
      {
        space: "organization",
        label: "全社の勤怠",
        href: "/organization/attendances",
        visibility: { kind: "permission", permission: "attendance:read:all" },
      },
      {
        space: "organization",
        label: "時間外の集計",
        href: "/organization/attendances/overtime",
        visibility: everyone,
      },
    ],
  },
  {
    slug: "leave",
    tier: "app-default",
    status: "development",
    group: "time",
    icon: CalendarOff,
    prefetch: null,
    routes: [
      { space: "my", label: "休暇", href: "/my/leaves", visibility: everyone },
      {
        space: "teams",
        label: "休暇",
        href: "/teams/:team/leaves",
        visibility: {
          kind: "any-permission",
          permissions: ["leave:read:department", "leave:read:all"],
        },
      },
      {
        space: "organization",
        label: "全社の休暇",
        href: "/organization/leaves",
        visibility: { kind: "permission", permission: "leave:read:all" },
      },
    ],
  },
  {
    slug: "shifts",
    tier: "app-default",
    status: "development",
    group: "time",
    icon: CalendarDays,
    prefetch: null,
    routes: [
      { space: "my", label: "シフト", href: "/my/shifts", visibility: everyone },
      {
        space: "organization",
        label: "シフト割当",
        href: "/organization/shift-assignments",
        visibility: { kind: "permission", permission: "shift:manage" },
      },
      {
        space: "organization",
        label: "シフトパターン",
        href: "/organization/shift-patterns",
        visibility: { kind: "permission", permission: "shift:manage" },
      },
      {
        space: "organization",
        label: "シフト交代の横断",
        href: "/organization/shift-swaps",
        visibility: { kind: "permission", permission: "shift_swap:read:all" },
      },
    ],
  },
  {
    slug: "company-calendar",
    tier: "app-default",
    status: "development",
    group: "time",
    icon: CalendarDays,
    prefetch: null,
    routes: [
      {
        space: "organization",
        label: "カレンダー",
        href: "/organization/calendars",
        visibility: everyone,
      },
    ],
  },
  {
    slug: "applications",
    tier: "company",
    status: "available",
    group: "requests",
    icon: FileText,
    prefetch: null,
    routes: [
      { space: "my", label: "申請", href: "/my/applications", visibility: everyone },
      {
        space: "teams",
        label: "申請",
        href: "/teams/:team/applications",
        visibility: {
          kind: "any-permission",
          permissions: ["application:read:department", "application:read:all"],
        },
      },
      {
        space: "organization",
        label: "全社の申請",
        href: "/organization/applications",
        visibility: { kind: "permission", permission: "application:read:all" },
      },
      {
        space: "organization",
        label: "申請テンプレート",
        href: "/organization/application-templates",
        visibility: { kind: "permission", permission: "application_template:manage" },
      },
      {
        space: "organization",
        label: "ワークフロー修復",
        href: "/organization/workflow-repairs",
        visibility: {
          kind: "all-permissions",
          permissions: ["application:read:all", "application_template:manage"],
        },
      },
    ],
  },
  {
    slug: "expenses",
    tier: "app-default",
    status: "development",
    group: "requests",
    icon: Coins,
    prefetch: null,
    routes: [
      { space: "my", label: "経費", href: "/my/expenses", visibility: everyone },
      {
        space: "organization",
        label: "全社の経費",
        href: "/organization/expenses",
        visibility: { kind: "permission", permission: "expense:read:all" },
      },
    ],
  },
  {
    slug: "business-trips",
    tier: "app-default",
    status: "development",
    group: "requests",
    icon: Plane,
    prefetch: null,
    routes: [
      { space: "my", label: "出張", href: "/my/business-trips", visibility: everyone },
      {
        space: "organization",
        label: "出張の横断",
        href: "/organization/business-trips",
        visibility: { kind: "permission", permission: "business_trip:read:all" },
      },
    ],
  },
  {
    slug: "certificate-requests",
    tier: "company",
    status: "development",
    group: "requests",
    icon: ScrollText,
    prefetch: null,
    routes: [
      {
        space: "my",
        label: "証明書",
        href: "/my/certificate-requests",
        visibility: everyone,
      },
      {
        space: "organization",
        label: "証明書の横断",
        href: "/organization/certificate-requests",
        visibility: { kind: "permission", permission: "certificate_request:read:all" },
      },
    ],
  },
  {
    slug: "life-events",
    tier: "app-default",
    status: "development",
    group: "requests",
    icon: PartyPopper,
    prefetch: null,
    routes: [
      { space: "my", label: "ライフイベント", href: "/my/life-events", visibility: everyone },
      {
        space: "organization",
        label: "ライフイベントの横断",
        href: "/organization/life-events",
        visibility: { kind: "permission", permission: "life_event:read:all" },
      },
    ],
  },
  {
    slug: "family-care-leave",
    tier: "app-default",
    status: "development",
    group: "requests",
    icon: HandHelping,
    prefetch: null,
    routes: [
      {
        space: "my",
        label: "休業",
        href: "/my/family-care-leaves",
        visibility: everyone,
      },
      {
        space: "organization",
        label: "休業の横断",
        href: "/organization/family-care-leaves",
        visibility: { kind: "permission", permission: "family_care_leave:read:all" },
      },
    ],
  },
  {
    slug: "resignations",
    tier: "company",
    status: "development",
    group: "requests",
    icon: UserMinus,
    prefetch: null,
    routes: [
      { space: "my", label: "退職", href: "/my/resignations", visibility: everyone },
      {
        space: "organization",
        label: "退職の横断",
        href: "/organization/resignations",
        visibility: { kind: "permission", permission: "resignation:read:all" },
      },
    ],
  },
  {
    slug: "ringi",
    tier: "app-default",
    status: "development",
    group: "requests",
    icon: FileText,
    prefetch: null,
    routes: [
      { space: "my", label: "稟議", href: "/my/ringis", visibility: everyone },
      {
        space: "organization",
        label: "稟議の横断",
        href: "/organization/ringis",
        visibility: { kind: "permission", permission: "ringi:read:all" },
      },
    ],
  },
  {
    slug: "antisocial-checks",
    tier: "app-default",
    status: "development",
    group: "requests",
    icon: ShieldCheck,
    prefetch: null,
    routes: [
      {
        space: "my",
        label: "反社チェック",
        href: "/my/antisocial-checks",
        visibility: everyone,
      },
    ],
  },
  {
    slug: "approval-delegations",
    tier: "company",
    status: "development",
    group: "requests",
    icon: ClipboardCheck,
    prefetch: null,
    routes: [
      {
        space: "teams",
        label: "代理承認の設定",
        href: "/teams/approval-delegations",
        visibility: {
          kind: "any-permission",
          permissions: ["goal:read:reports", "attendance:read:reports", "leave:read:reports"],
        },
      },
    ],
  },
  {
    slug: "employees",
    tier: "company",
    status: "available",
    group: "people",
    icon: Users,
    prefetch: null,
    routes: [
      {
        space: "organization",
        label: "従業員",
        href: "/organization/employees",
        visibility: everyone,
      },
    ],
  },
  {
    slug: "departments",
    tier: "company",
    status: "available",
    group: "people",
    icon: GitBranch,
    prefetch: null,
    routes: [
      {
        space: "organization",
        label: "組織図",
        href: "/organization/departments",
        visibility: everyone,
      },
    ],
  },
  {
    slug: "team-management",
    tier: "company",
    status: "development",
    group: "people",
    icon: Users,
    prefetch: null,
    routes: [
      {
        space: "teams",
        label: "マイチーム",
        href: "/teams/reports",
        visibility: {
          kind: "any-permission",
          permissions: ["goal:read:reports", "attendance:read:reports", "leave:read:reports"],
        },
      },
      {
        space: "teams",
        label: "メンバー",
        href: "/teams/:team/members",
        visibility: everyone,
      },
    ],
  },
  {
    slug: "onboarding",
    tier: "company",
    status: "development",
    group: "people",
    icon: ClipboardList,
    prefetch: null,
    routes: [
      {
        space: "my",
        label: "オンボーディング",
        href: "/my/onboarding-tasks",
        visibility: everyone,
      },
      {
        space: "organization",
        label: "オンボーディング設計",
        href: "/organization/onboarding-templates",
        visibility: { kind: "permission", permission: "onboarding:manage" },
      },
      {
        space: "organization",
        label: "オンボーディング進捗",
        href: "/organization/onboarding-assignments",
        visibility: { kind: "permission", permission: "onboarding:view:all" },
      },
    ],
  },
  {
    slug: "recruitment",
    tier: "app-default",
    status: "development",
    group: "people",
    icon: Users,
    prefetch: null,
    routes: [
      {
        space: "organization",
        label: "採用",
        href: "/organization/recruitments",
        visibility: { kind: "permission", permission: "recruitment:manage" },
      },
    ],
  },
  {
    slug: "headcount-plans",
    tier: "app-default",
    status: "development",
    group: "people",
    icon: Users,
    prefetch: null,
    routes: [
      {
        space: "organization",
        label: "人員計画",
        href: "/organization/headcount-plans",
        visibility: { kind: "permission", permission: "headcount_plan:read:all" },
      },
    ],
  },
  {
    slug: "health-checkups",
    tier: "app-default",
    status: "development",
    group: "people",
    icon: ClipboardCheck,
    prefetch: null,
    routes: [
      {
        space: "organization",
        label: "健診の実施記録",
        href: "/organization/health-checkups",
        visibility: { kind: "permission", permission: "health_checkup:read:all" },
      },
    ],
  },
  {
    slug: "work-accidents",
    tier: "app-default",
    status: "development",
    group: "people",
    icon: TriangleAlert,
    prefetch: null,
    routes: [
      {
        space: "organization",
        label: "労災・事故",
        href: "/organization/work-accidents",
        visibility: { kind: "permission", permission: "work_accident:read:all" },
      },
    ],
  },
  {
    slug: "grades",
    tier: "company",
    status: "development",
    group: "people",
    icon: Award,
    prefetch: null,
    routes: [
      {
        space: "organization",
        label: "等級",
        href: "/organization/grades",
        visibility: everyone,
      },
    ],
  },
  {
    slug: "positions",
    tier: "company",
    status: "development",
    group: "people",
    icon: Briefcase,
    prefetch: null,
    routes: [
      {
        space: "organization",
        label: "役職",
        href: "/organization/positions",
        visibility: everyone,
      },
    ],
  },
  {
    slug: "certifications",
    tier: "app-default",
    status: "development",
    group: "people",
    icon: Award,
    prefetch: null,
    routes: [
      {
        space: "organization",
        label: "資格・免許",
        href: "/organization/certifications",
        visibility: everyone,
      },
    ],
  },
  {
    slug: "performance-reviews",
    tier: "app-opt-in",
    status: "development",
    group: "growth",
    icon: ClipboardCheck,
    prefetch: null,
    routes: [
      { space: "my", label: "評価", href: "/my/reviews", visibility: everyone },
      {
        space: "organization",
        label: "評価サイクル",
        href: "/organization/review-cycles",
        visibility: { kind: "permission", permission: "review:administer" },
      },
      {
        space: "organization",
        label: "評価結果",
        href: "/organization/reviews",
        visibility: { kind: "permission", permission: "review:administer" },
      },
    ],
  },
  {
    slug: "goals",
    tier: "app-opt-in",
    status: "development",
    group: "growth",
    icon: Target,
    prefetch: null,
    routes: [
      {
        space: "teams",
        label: "目標",
        href: "/teams/:team/goals",
        visibility: {
          kind: "any-permission",
          permissions: ["goal:read:department", "goal:read:all"],
        },
      },
      {
        space: "organization",
        label: "目標",
        href: "/organization/goals",
        visibility: everyone,
      },
    ],
  },
  {
    slug: "skills",
    tier: "app-opt-in",
    status: "development",
    group: "growth",
    icon: Sparkles,
    prefetch: null,
    routes: [
      { space: "my", label: "スキル", href: "/my/skills", visibility: everyone },
      {
        space: "organization",
        label: "スキル一覧",
        href: "/organization/skills",
        visibility: everyone,
      },
    ],
  },
  {
    slug: "career",
    tier: "app-opt-in",
    status: "development",
    group: "growth",
    icon: Briefcase,
    prefetch: null,
    routes: [
      { space: "my", label: "キャリア", href: "/my/career", visibility: everyone },
      {
        space: "organization",
        label: "社内公募",
        href: "/organization/job-postings",
        visibility: everyone,
      },
    ],
  },
  {
    slug: "training",
    tier: "app-opt-in",
    status: "development",
    group: "growth",
    icon: GraduationCap,
    prefetch: null,
    routes: [
      { space: "my", label: "研修", href: "/my/trainings", visibility: everyone },
      {
        space: "organization",
        label: "研修コース",
        href: "/organization/trainings",
        visibility: everyone,
      },
    ],
  },
  {
    slug: "one-on-ones",
    tier: "app-opt-in",
    status: "development",
    group: "growth",
    icon: CalendarClock,
    prefetch: null,
    routes: [
      { space: "my", label: "1on1", href: "/my/oneonones", visibility: everyone },
      {
        space: "teams",
        label: "1on1",
        href: "/teams/:team/oneonones",
        visibility: {
          kind: "any-permission",
          permissions: ["oneonone:read:department"],
        },
      },
    ],
  },
  {
    slug: "thanks",
    tier: "app-opt-in",
    status: "development",
    group: "growth",
    icon: HeartHandshake,
    prefetch: null,
    routes: [
      {
        space: "my",
        label: "サンクス履歴",
        href: "/my/thanks",
        visibility: everyone,
      },
      {
        space: "organization",
        label: "サンクス",
        href: "/organization/thanks",
        visibility: everyone,
      },
      {
        space: "organization",
        label: "景品",
        href: "/organization/rewards",
        visibility: everyone,
      },
      {
        space: "organization",
        label: "サンクス交換の横断",
        href: "/organization/thanks-redemptions",
        visibility: { kind: "permission", permission: "thanks_redemption:read:all" },
      },
    ],
  },
  {
    slug: "surveys",
    tier: "app-opt-in",
    status: "development",
    group: "growth",
    icon: MessagesSquare,
    prefetch: null,
    routes: [
      {
        space: "organization",
        label: "サーベイ",
        href: "/organization/surveys",
        visibility: everyone,
      },
      {
        space: "my",
        label: "自分の回答",
        href: "/my/survey-responses",
        visibility: everyone,
      },
    ],
  },
  {
    slug: "commendations",
    tier: "app-default",
    status: "development",
    group: "growth",
    icon: Award,
    prefetch: null,
    routes: [
      {
        space: "organization",
        label: "表彰",
        href: "/organization/commendations",
        visibility: everyone,
      },
    ],
  },
  {
    slug: "knowledge",
    tier: "app-opt-in",
    status: "development",
    group: "communication",
    icon: BookOpen,
    prefetch: null,
    routes: [
      {
        space: "organization",
        label: "ナレッジ",
        href: "/organization/knowledge-articles",
        visibility: everyone,
      },
    ],
  },
  {
    slug: "announcements",
    tier: "company",
    status: "development",
    group: "communication",
    icon: Bell,
    prefetch: null,
    routes: [
      {
        space: "organization",
        label: "アナウンス",
        href: "/organization/announcements",
        visibility: everyone,
      },
    ],
  },
  {
    slug: "regulations",
    tier: "company",
    status: "development",
    group: "governance",
    icon: BookOpenCheck,
    prefetch: null,
    routes: [
      {
        space: "organization",
        label: "規程集",
        href: "/organization/regulations",
        visibility: everyone,
      },
    ],
  },
  {
    slug: "assets",
    tier: "app-default",
    status: "development",
    group: "workplace",
    icon: Boxes,
    prefetch: null,
    routes: [
      { space: "my", label: "貸与品", href: "/my/assets", visibility: everyone },
      {
        space: "organization",
        label: "備品",
        href: "/organization/assets",
        visibility: everyone,
      },
      {
        space: "organization",
        label: "棚卸し",
        href: "/organization/stocktakes",
        visibility: { kind: "permission", permission: "asset:manage" },
      },
    ],
  },
  {
    slug: "rooms",
    tier: "app-default",
    status: "development",
    group: "workplace",
    icon: DoorOpen,
    prefetch: null,
    routes: [
      {
        space: "my",
        label: "会議室の予約",
        href: "/my/room-reservations",
        visibility: everyone,
      },
      {
        space: "organization",
        label: "会議室",
        href: "/organization/rooms",
        visibility: everyone,
      },
      {
        space: "organization",
        label: "会議室マスタ",
        href: "/organization/rooms/manage",
        visibility: { kind: "permission", permission: "room:manage" },
      },
    ],
  },
  {
    slug: "rentals",
    tier: "app-default",
    status: "development",
    group: "workplace",
    icon: Package,
    prefetch: null,
    routes: [
      { space: "my", label: "レンタル", href: "/my/rentals", visibility: everyone },
      {
        space: "organization",
        label: "レンタルの横断",
        href: "/organization/rentals",
        visibility: { kind: "permission", permission: "rental:read:all" },
      },
    ],
  },
  {
    slug: "meetings",
    tier: "app-default",
    status: "development",
    group: "governance",
    icon: CalendarDays,
    prefetch: null,
    routes: [
      {
        space: "organization",
        label: "会議体",
        href: "/organization/meetings",
        visibility: everyone,
      },
    ],
  },
  {
    slug: "decisions",
    tier: "company",
    status: "development",
    group: "governance",
    icon: BookOpenCheck,
    prefetch: null,
    routes: [
      {
        space: "organization",
        label: "意思決定記録",
        href: "/organization/decisions",
        visibility: everyone,
      },
    ],
  },
  {
    slug: "partners",
    tier: "app-default",
    status: "development",
    group: "governance",
    icon: Building2,
    prefetch: null,
    routes: [
      {
        space: "organization",
        label: "取引先",
        href: "/organization/partners",
        visibility: everyone,
      },
    ],
  },
  {
    slug: "management-dashboard",
    tier: "app-opt-in",
    status: "retirement-candidate",
    group: "governance",
    icon: LayoutDashboard,
    prefetch: null,
    routes: [
      {
        space: "organization",
        label: "経営ダッシュボード",
        href: "/organization/dashboards/management",
        visibility: { kind: "permission", permission: "management_dashboard:view" },
      },
    ],
  },
  {
    slug: "budgets",
    tier: "app-default",
    status: "development",
    group: "governance",
    icon: Wallet,
    prefetch: null,
    routes: [
      {
        space: "organization",
        label: "予算",
        href: "/organization/budgets",
        visibility: { kind: "permission", permission: "budget:manage" },
      },
    ],
  },
  {
    slug: "document-ledger",
    tier: "company",
    status: "development",
    group: "governance",
    icon: FileText,
    prefetch: null,
    routes: [
      {
        space: "organization",
        label: "文書台帳",
        href: "/organization/documents",
        visibility: { kind: "permission", permission: "document:read:all" },
      },
    ],
  },
  {
    slug: "governance",
    tier: "company",
    status: "development",
    group: "governance",
    icon: ShieldCheck,
    prefetch: null,
    routes: [
      {
        space: "organization",
        label: "規程・手続き",
        href: "/organization/governance",
        visibility: { kind: "permission", permission: "governance:read" },
      },
    ],
  },
  {
    slug: "roles",
    tier: "system",
    status: "available",
    group: "system",
    icon: KeyRound,
    prefetch: null,
    routes: [
      {
        space: "system",
        label: "ロール",
        href: "/system/roles",
        visibility: { kind: "permission", permission: "iam:read" },
      },
    ],
  },
  {
    slug: "accounts",
    tier: "system",
    status: "available",
    group: "system",
    icon: UserCog,
    prefetch: null,
    routes: [
      {
        space: "system",
        label: "アカウント",
        href: "/system/accounts",
        visibility: { kind: "permission", permission: "iam:read" },
      },
    ],
  },
  {
    slug: "audit",
    tier: "system",
    status: "available",
    group: "system",
    icon: FileClock,
    prefetch: false,
    routes: [
      {
        space: "system",
        label: "監査ログ",
        href: "/system/audit-events",
        visibility: { kind: "permission", permission: "audit:read" },
      },
    ],
  },
  {
    slug: "software-licenses",
    tier: "app-default",
    status: "development",
    group: "system",
    icon: Laptop,
    prefetch: null,
    routes: [
      {
        space: "system",
        label: "ライセンス",
        href: "/system/licenses",
        visibility: { kind: "permission", permission: "license:read:all" },
      },
    ],
  },
  {
    slug: "it-incidents",
    tier: "app-default",
    status: "development",
    group: "system",
    icon: TriangleAlert,
    prefetch: null,
    routes: [
      {
        space: "system",
        label: "IT インシデント",
        href: "/system/it-incidents",
        visibility: { kind: "permission", permission: "it_incident:read:all" },
      },
    ],
  },
  {
    slug: "batches",
    tier: "system",
    status: "available",
    group: "system",
    icon: Wrench,
    prefetch: null,
    routes: [
      {
        space: "system",
        label: "バッチ",
        href: "/system/batches",
        visibility: { kind: "permission", permission: "batch:view" },
      },
    ],
  },
  {
    slug: "settings",
    tier: "system",
    status: "available",
    group: "settings",
    icon: Settings,
    prefetch: null,
    // 設定の入口はサイドバー下部のユーザーメニュー（設定モーダル）へ寄せたため、ここには出さない。
    routes: [],
  },
]

export const featureGroupOrder: ReadonlyArray<FeatureGroup> = [
  "overview",
  "people",
  "time",
  "requests",
  "growth",
  "communication",
  "workplace",
  "governance",
  "system",
  "settings",
]

export const featureGroupLabels: Record<FeatureGroup, string> = {
  overview: "概要",
  people: "人と組織",
  time: "時間と予定",
  requests: "申請と手続き",
  growth: "成長と評価",
  communication: "情報共有",
  workplace: "資産と施設",
  governance: "経営と統制",
  system: "システム運用",
  settings: "個人設定",
}

export const featureTierLabels: Record<FeatureTier, string> = {
  system: "システム層",
  company: "company",
  "app-default": "app-default",
  "app-opt-in": "app-opt-in",
}

export const featureStatusLabels: Record<FeatureStatus, string> = {
  available: "使用可能",
  development: "開発中",
  "retirement-candidate": "廃止候補",
}
