export type CompanyResourceValidationCode =
  | "invalid_identifier"
  | "invalid_revision"
  | "invalid_period"
  | "invalid_attributes"
  | "invalid_resource"
  | "invalid_organization"
  | "invalid_change"
  | "invalid_query"
export type OrganizationalAuthorityErrorCode =
  | "organizational_authority_snapshot_invalid"
  | "organizational_authority_employee_duplicate"
  | "organizational_authority_state_as_of_mismatch"
  | "organizational_authority_state_invalid"
  | "organizational_authority_period_invalid"
  | "organizational_authority_period_duplicate"
  | "organizational_authority_employee_reference_missing"
  | "organizational_authority_subject_missing"
  | "organizational_authority_account_employee_duplicate"
  | "organizational_authority_account_duplicate"
  | "organizational_authority_account_employee_missing"
  | "organizational_authority_manager_cycle"
export type WorkforceStateResolutionCode =
  | "employment_state_ambiguous"
  | "status_state_missing"
  | "status_state_ambiguous"
  | "primary_assignment_state_ambiguous"
export type OrganizationChangeValidationCode =
  | "empty_change"
  | "invalid_revision"
  | "invalid_operation"
  | "invalid_audit"
  | "invalid_identity"
  | "unknown_employee"
  | "invalid_organization"
  | "invalid_workforce"
export type AccountEmployeeLinkResolutionCode =
  | "account_link_ambiguous"
  | "account_link_account_mismatch"
  | "account_link_employee_mismatch"
